prequals = """
Ballard, E. / Ballard, J.
Chen, N. / Lo, E.
LaRonge, J. / Wiesner, G.
Picchiottino, B. / Rush, J.
Crone, J. / James, N.
Noble, I. / Offutt, B.
Fisher, A. / Kang, J.
Amason, C. / Brandt, S.
"""

rankings = """
DuFault, J. / Higginbotham, T.
Burson, M. / Tofte, K.
Ko, S. / McCoy, C.
Daniel, C. / Light, A.
Brown, S. / Truly, J.
Koch, B. / Koch, C.
Harrison, A. / Stowe, H.
Mosbey, J. / Shivam, A.
**Aryani, J. / McDonald, E.
Brewster, A. / Raymer, W.
Alles, C. / Imp, A.
Mann, A. / Smith, M.
Im, O. / Majors, E.
Hogancamp, R. / Martin, E.
Chahyadi, J. / Nelson, I.
Culp, E. / Culp, W.
Behrens, T. / Christodoulou, S.
Johnson, K. / Storz, E.
Piper, I. / Stokarski, S.
Martinez, S. / Rush, J.
Buck, L. / Buck, P.
Behrens, G. / Kean, C.
Richards, M. / Richards, S.
Aryani, J. / Dickey, A.
Brown, I. / Brown, L.
Moore, A. / Su, D.
Fairfax, E. / Gordon, W.
Chen, H. / Spencer, N.
Graham, E. / Shrode, N.
James, B. / Offutt, W.
Chu, J. / Chu, N.
Yoder, X. / Yoder, X.
Glessner, A. / Pratt, A.
Li, E. / Li, E.
Canna, C. / Johnson, D.
Bigler, C. / Knight, E.
Kirkpatrick, K. / McIntyre, T.
Bonar, L. / Young, R.
Courville, J. / Davis, S.
Brindis De Salas, I. / Stanton, P.
Gelok, M. / Sanchez, N.
Meredith, R. / Taylor, L.
Mackie, T. / Raub, H.
Hall, M. / Slayton, A.
Howard, J. / Kaiser, E.
Swan, S. / White, C.
Parsley, E. / Parsley, J.
Gutierrez, B. / Riehle, M.
Dignan, C. / Dignan, S.
Blacker, R. / Paul, J.
Phillips, A. / Phillips, M.
Formo, A. / Zylstra, C.
Bosier, J. / Bosier, M.
Bechtold, A. / John, E.
Mann, J. / Scalph, W.
Buck, J. / Stoub, P.
Crosby, L. / Crosby, M.
Pope, J. / Swick, J.
Bluel, A. / Pettys, K.
Sussmann, B. / Sussmann, X.
McDonald, B. / McDonald, S.
Brummund, D. / McKay, L.
Musgrave, A. / Tuck, I.
Corley, M. / Marshall, N.
McCoy, P. / Tremaine, M.
Sabo, S. / Wilson, C.
Barron, T. / Wentworth, N.
Hill, I. / Hill, R.
Noble, A. / Sun, D.
Cohen, T. / Davis, J.
Eichholz, A. / Porter, A.
Graham, A. / Price, K.
Oliver, E. / Osborne, J.
Hessler, J. / Hisler, T.
DuFault, B. / DuFault, J.
Low, M. / Low, Z.
Pozayt, E. / Pozayt, J.
Batchelder, O. / Mann, R.
Butts, C. / Paul, J.
Ching, K. / Dang, Z.
Lombardozzi, D. / Tirone, C.
Mowry, N. / Nagle, T.
Gouge, B. / Hightower, N.
Kwan, J. / Kwan, T.
Behring, T. / Martinez, S.
Lindsay, J. / Wiesner, G.
Ji, C. / Ji, J.
Markwort, E. / Markwort, L.
Baker, J. / Slobodnik, D.
Brown, N. / Sanchez, N.
Distefano, D. / Rorem, Q.
Gamble, E. / Wiesner, G.
Moore, A. / Moore, E.
Krmpotich, D. / Stoub, L.
Travis, D. / Trull, L.
Bruce, R. / Santos, A.
Ser, E. / Ser, E.
Mamaloukas, E. / Wu, M.
Cortez, A. / Cortez, L.
Chen, A. / Kuykendall, W.
Aryani, R. / Dickey, M.
Gardner, J. / Luft, N.
Cordova, M. / Riehle, J.
Jonson, E. / Young, A.
Miller, L. / Miller, M.
Joshua, A. / Mazzucco, E.
Suemoto, I. / Suemoto, K.
Tong, E. / Tong, H.
Eng, N. / Jin, E.
Lewis, J. / Wood, B.
Overmiller, J. / Pettys, L.
Baruffi, M. / Crory, J.
Graham, C. / Pruett, E.
Slayton, D. / Slayton, J.
Ballard, K. / Stanford, J.
Hester, E. / Hester, L.
Majors, B. / Majors, L.
Bargen, A. / Morton, R.
Andress, M. / Johnson, C.
Chaparro, A. / Chaparro, N.
LeBlanc, L. / Wilson, C.
Peterson, N. / Peterson, S.
Thompson, P. / Thompson, S.
Phillips, D. / Phillips, J.
Lewis, T. / Singh, M.
Oliver, J. / Oliver, K.
Davis, D. / Richards, A.
Higashi, A. / Higashi, J.
Harper, M. / Joseph, M.
Castrinos, J. / Wanner, S.
Haslett, M. / Schroeder, J.
Cronenberger, A. / Cronenberger, Z.
Lutz, N. / Schroeder, J.
McGuire, S. / Sumner, A.
Elshoff, L. / Thomas, A.
Schroeder, E. / Smith, M.
Glessner, J. / Johnson, B.
Kean, C. / WIlliams, M.
Elliott, C. / Kagy, J.
Eby, S. / Lo, K.
Lindstrom, B. / Lindstrom, J.
Gilchrist, R. / Husted, D.
Green, I. / Lee, J.
Milligan, J. / Schneider, W.
Piper, J. / Piper, M.
Ramsay, P. / Ridings, P.
Blondet, S. / Hogan, E.
Jaenchen, E. / Jaenchen, I.
Chu, A. / York, K.
Higginbotham, T. / Nelson, G.
Hall, M. / Martin, A.
Ballard, A. / Ballard, K.
Batten, L. / Mawdesley, A.
Clark, L. / Pedone, J.
Gardner, M. / Rowe, J.
Buck, J. / Buck, P.
Burson, C. / Burson, P.
Benyamin, D. / Milik, J.
Brown, N. / Smaistrla, C.
DuFault, B. / Johnson, J.
Smith, L. / Smith, N.
Benyamin, D. / Crismariu, D.
Heuber, H. / Luft, N.
Phillips, K. / Phillips, R.
Becker, A. / Brindis De Salas, T.
Cobbs, S. / Parsley, C.
Behrens, T. / Reader, J.
Dickey, A. / Dickey, M.
Feenstra, C. / Feenstra, C.
McClure, C. / Zylstra, G.
White, A. / White, M.
Davis, J. / Nelson, G.
Hoffpauir, R. / Pritchard, D.
Minotti, L. / Osborn, A.
Lannie, D. / Sabo, S.
Childs, A. / Frater, A.
Rice, E. / Riley, J.
Brewster, S. / Shoemaker, E.
Gutierrez, A. / Voeller, D.
Lannie, D. / Wagner, V.
Lasley, H. / Palmisano, C.
Mazahreh, J. / Mazahreh, P.
DelGrosso, K. / Ngwa, G.
Shoda, K. / Woodward, A.
Bomberger, K. / Garlock, L.
Hemp, T. / Pickering, S.
Kerr, R. / Kerr, T.
Moore, L. / Su, T.
Centeno, J. / Rodriguez, L.
Clark, S. / Thies, K.
Davis, J. / Koch, B.
Jin, J. / Nelson, G.
Hughes, J. / Kusnadi, E.
Mendoza, D. / Wei, J.
Koch, D. / Koch, M.
Wadzeck, N. / Whitacre, K.
Claghorn, J. / Nagel, K.
Howard, J. / Oliver, S.
Chahyadi, J. / Springer, J.
Hall, M. / Hall, M.
Hughes, C. / Rauscher, D.
Leibig, T. / Weihmann, D.
Baumgartner, D. / RYAN, J.
Davis, A. / Gremillion, L.
Hirschy, J. / Nicholes, B.
Knobloch, A. / Knobloch, B.
Raub, L. / Ruiz, J.
Andrews, M. / Andrews, P.
Heffernan, T. / Pepiot, C.
Jennings, K. / Landers, R.
Childs, A. / Crosby, M.
Heffernan, I. / Ryan, C.
Hill, A. / Hill, S.
Lusk, A. / Thompson, M.
Jaenchen, A. / Skowron, M.
Heavener, A. / Miller, E.
Aladejebi, O. / Smith, S.
Price, C. / Price, E.
Martinez, I. / Rush, M.
Davenport, N. / O'Connors, L.
Cookston, V. / Metcalfe, L.
"""